---
title: "GGPLOT pre-req"
output: html_document
date: "2026-04-03"
---

library(ggplot2)
library(tidyverse)

# Load the dataset
```{r}
heightdata <- read.csv("C:/Users/norba/Downloads/height_data_clean.csv")
```


#plot that shows trend line of height_cm/time, with a separate line for each population and convert date
```{r}
heightdata$survey_date <- as.Date(heightdata$survey_date, format = "%Y-%m-%d")
```


# Plot the trend lines, separate by population
```{r}
ggplot(data = heightdata, mapping = aes(x = survey_date, y = height_cm, color = pop)) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Height Trend Over Time by Population",
       x = "Survey Date",
       y = "Height (cm)") +
  theme_minimal()
```
  

#subset data selecting for January 23, 2023 only
```{r}
subsetdata<-heightdata%>%
filter (survey_date == "2023-01-27")%>%
group_by(pop)
```

#Boxplot subset data
```{r}
ggplot(data= subsetdata, aes(x=survey_date, y=height_cm, color=pop))+
geom_boxplot()
```


## Plot the trend lines, separate by population with data points
```{r}
ggplot(data = heightdata, mapping = aes(x = survey_date, y = height_cm, color = pop)) +
  geom_smooth(method = "lm", se = FALSE) +
  geom_point()+
  labs(title = "Height Trend Over Time by Population",
       x = "Survey Date",
       y = "Height (cm)") +
  theme_minimal()
```


